### Import libraries

In [2]:
import pandas as pd
import numpy as np 
from sklearn.ensemble import IsolationForest
import joblib

### Load Data

In [7]:
employees = pd.read_csv('../data/employees.csv')
payroll = pd.read_csv('../data/payroll.csv')
dept = pd.read_csv('../data/departments.csv')

In [12]:
dept

   dept_id    dept_name
0        1        Sales
1        2  Engineering
2        3           HR
3        4      Finance
4        5   Operations

In [8]:
payroll

,payroll_id,employee_id,pay_period,gross_pay,deductions,net_pay,overtime_hours
0,1,1,2026-02-28,6147.79,1528.66,4619.13,10
1,2,2,2026-02-28,5279.71,872.66,4407.05,10
2,3,3,2026-02-28,6081.91,1025.75,5056.15,5
3,4,4,2026-02-28,6903.75,1232.39,5671.36,0
4,5,5,2026-02-28,4707.25,787.70,3919.55,0
...,...,...,...,...,...,...,...
496,497,497,2026-02-28,3703.42,921.33,2782.09,0
497,498,498,2026-02-28,4762.00,779.27,3982.73,0
498,499,499,2026-02-28,3905.42,857.30,3048.12,0
499,500,500,2026-02-28,3271.50,623.00,2648.50,0
500,501,501,2026-02-28,5765.81,924.90,4840.91,20

In [9]:
employees

,employee_id,first_name,last_name,ssn,email,department_id,hire_date,salary,is_active
0,1,Harry,Mason,757-41-5089,codythompson@example.net,1.0,2026-02-04,67450,True
1,2,Carrie,Cortez,543-28-3579,joan05@example.com,1.0,2024-08-19,57926,True
2,3,Leah,Johnson,641-54-9311,debbie71@example.net,3.0,2024-08-10,69715,True
3,4,Steven,Tyler,658-03-5889,gibsonwilliam@example.com,2.0,2023-06-26,82845,True
4,5,Henry,Clark,730-07-8681,teresashepard@example.net,2.0,2022-11-15,56487,True
...,...,...,...,...,...,...,...,...,...
496,497,Jennifer,Davis,133-19-0028,elizabethmiller@example.org,4.0,2022-07-21,44441,True
497,498,Kelly,Hansen,194-51-8915,thudson@example.net,2.0,2022-12-02,57144,True
498,499,Jeff,Hampton,187-34-3519,uwebster@example.com,5.0,2023-06-30,46865,True
499,500,Marvin,Frederick,789-73-9813,alexander26@example.com,4.0,2023-02-24,39258,True
500,501,Ghost,Employee,862-86-7867,ibeck@example.org,3.0,2026-02-05,58265,True

### Merge

In [14]:
df = payroll.merge(employees, on='employee_id', how='left')
df = df.merge(dept, left_on= 'department_id', right_on='dept_id', how='left')

,payroll_id,employee_id,pay_period,gross_pay,deductions,net_pay,overtime_hours,first_name,last_name,ssn,email,department_id,hire_date,salary,is_active,dept_id,dept_name
0,1,1,2026-02-28,6147.79,1528.66,4619.13,10,Harry,Mason,757-41-5089,codythompson@example.net,1.0,2026-02-04,67450,True,1.0,Sales
1,2,2,2026-02-28,5279.71,872.66,4407.05,10,Carrie,Cortez,543-28-3579,joan05@example.com,1.0,2024-08-19,57926,True,1.0,Sales
2,3,3,2026-02-28,6081.91,1025.75,5056.15,5,Leah,Johnson,641-54-9311,debbie71@example.net,3.0,2024-08-10,69715,True,3.0,HR
3,4,4,2026-02-28,6903.75,1232.39,5671.36,0,Steven,Tyler,658-03-5889,gibsonwilliam@example.com,2.0,2023-06-26,82845,True,2.0,Engineering
4,5,5,2026-02-28,4707.25,787.70,3919.55,0,Henry,Clark,730-07-8681,teresashepard@example.net,2.0,2022-11-15,56487,True,2.0,Engineering
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,497,497,2026-02-28,3703.42,921.33,2782.09,0,Jennifer,Davis,133-19-0028,elizabethmiller@example.org,4.0,2022-07-21,44441,True,4.0,Finance
497,498,498,2026-02-28,4762.00,779.27,3982.73,0,Kelly,Hansen,194-51-8915,thudson@example.net,2.0,2022-12-02,57144,True,2.0,Engineering
498,499,499,2026-02-28,3905.42,857.30,3048.12,0,Jeff,Hampton,187-34-3519,uwebster@example.com,5.0,2023-06-30,46865,True,5.0,Operations
499,500,500,2026-02-28,3271.50,623.00,2648.50,0,Marvin,Frederick,789-73-9813,alexander26@example.com,4.0,2023-02-24,39258,True,4.0,Finance
500,501,501,2026-02-28,5765.81,924.90,4840.91,20,Ghost,Employee,862-86-7867,ibeck@example.org,3.0,2026-02-05,58265,True,3.0,HR

### Feature engineering

In [17]:
df['salary_monthly'] = df['salary'] / 12
df['net_pay_ratio'] = df['net_pay'] / df['gross_pay'] # should be <1, ~0.8
df['deductions_ratio'] = df['deductions'] / df['gross_pay']
df['overtime_ratio'] = df['overtime_hours'] / 160 # overtime hours as fraction of monthly hours
df['gross_vs_salary'] = df['gross_pay'] / df['salary_monthly'] # should be >=1 if overtime, else ~1

### Handle missing and infinite values

In [22]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.fillna(0, inplace=True)

### Model training

In [25]:
features = ['gross_pay', 'deductions', 'net_pay', 'overtime_hours',
            'net_pay_ratio', 'deductions_ratio', 'overtime_ratio', 'gross_vs_salary']

X = df[features]

# Train Isolation Forest
model = IsolationForest(contamination=0.05, random_state=42)
df['anomaly_score'] = model.fit_predict(X)
df['anomaly_score'] = df['anomaly_score'].map({1: 0, -1: 1})  # 1 = anomaly


# Add negative scores for easier sorting
df['anomaly_decision'] = model.decision_function(X)

In [26]:
extemely_Suspicion = df[df['anomaly_decision'] < 0]
Large_negative_number

,payroll_id,employee_id,pay_period,gross_pay,deductions,net_pay,overtime_hours,first_name,last_name,ssn,...,is_active,dept_id,dept_name,salary_monthly,net_pay_ratio,deductions_ratio,overtime_ratio,gross_vs_salary,anomaly_score,anomaly_decision
14,15,15,2026-02-28,3110.44,524.75,2585.70,10,Marie,Owens,667-19-6736,...,True,2.0,Engineering,2843.833333,0.831297,0.168706,0.06250,1.093749,1,-0.010696
73,74,74,2026-02-28,8259.95,2052.47,6207.49,20,Justin,Gentry,001-31-4523,...,True,2.0,Engineering,6955.750000,0.751517,0.248485,0.12500,1.187500,1,-0.073350
74,75,75,2026-02-28,2617.19,633.58,1983.61,5,Rebecca,Craig,676-18-8322,...,True,5.0,Operations,2500.000000,0.757916,0.242084,0.03125,1.046876,1,-0.014225
86,87,87,2026-02-28,7008.29,1060.42,5947.87,15,David,Williamson,744-28-5007,...,True,3.0,HR,6144.250000,0.848691,0.151309,0.09375,1.140626,1,-0.004887
110,111,111,2026-02-28,2723.45,436.87,2286.58,5,Elizabeth,Ross,610-39-8926,...,True,2.0,Engineering,2601.500000,0.839589,0.160411,0.03125,1.046877,1,-0.034834
121,122,122,2026-02-28,4587.61,807.15,3780.45,20,Lori,Kennedy,304-78-4111,...,True,4.0,Finance,3863.250000,0.824057,0.175941,0.12500,1.187500,1,-0.001126
125,126,126,2026-02-28,8826.16,1583.82,7242.33,15,Joan,Bailey,881-91-0815,...,True,5.0,Operations,7738.000000,0.820553,0.179446,0.09375,1.140625,1,-0.048964
130,131,131,2026-02-28,3635.73,643.04,2992.69,20,Jonathan,White,633-91-9711,...,True,5.0,Operations,3061.666667,0.823133,0.176867,0.12500,1.187500,1,-0.040590
153,154,154,2026-02-28,6282.17,961.92,5320.26,20,Joseph,Carroll,728-87-9522,...,True,1.0,Sales,5290.250000,0.846883,0.153119,0.12500,1.187500,1,-0.015698
173,174,174,2026-02-28,6698.23,1573.55,5124.69,25,Andrew,White,774-43-8262,...,True,5.0,Operations,5426.416667,0.765081,0.234920,0.15625,1.234374,1,-0.049953
183,184,184,2026-02-28,6916.31,1610.75,5305.56,25,Melissa,Scott,052-57-4332,...,True,4.0,Finance,5603.083333,0.767108,0.232892,0.15625,1.234376,1,-0.051022
209,210,210,2026-02-28,9815.83,1885.97,7929.86,0,Emily,Johnson,219-22-5919,...,True,3.0,HR,9815.833333,0.807864,0.192136,0.00000,1.000000,1,-0.047442
222,223,223,2026-02-28,6956.08,1732.88,5223.20,20,Jennifer,Rogers,433-31-9315,...,True,1.0,Sales,5857.750000,0.750883,0.249117,0.12500,1.187500,1,-0.026549
300,301,301,2026-02-28,0.00,-150.75,0.00,0,Stephanie,Parker,481-30-7498,...,True,5.0,Operations,0.000000,0.000000,0.000000,0.00000,0.000000,1,-0.168521
314,315,315,2026-02-28,8186.17,1254.55,6931.62,25,Carlos,Salas,323-96-3347,...,True,4.0,Finance,6631.833333,0.846748,0.153252,0.15625,1.234375,1,-0.111241
323,324,324,2026-02-28,8329.36,1309.75,7019.61,10,William,Peters,555-02-1775,...,True,5.0,Operations,7615.416667,0.842755,0.157245,0.06250,1.093750,1,-0.012964
374,375,375,2026-02-28,8773.02,1835.62,6937.40,15,Samantha,Mora,120-43-1058,...,True,4.0,Finance,7691.416667,0.790765,0.209235,0.09375,1.140625,1,-0.036620
399,400,400,2026-02-28,7774.86,1841.30,5933.56,20,Chris,Smith,775-14-8566,...,True,5.0,Operations,6547.250000,0.763173,0.236827,0.12500,1.187500,1,-0.035782
400,401,401,2026-02-28,0.00,512.93,0.00,0,Brianna,Brennan,120-79-7825,...,True,0.0,0,3006.916667,0.000000,0.000000,0.00000,0.000000,1,-0.150469
419,420,420,2026-02-28,6037.65,923.99,5113.65,20,Desiree,Anderson,762-26-6387,...,True,3.0,HR,5084.333333,0.846960,0.153038,0.12500,1.187501,1,-0.017506
420,421,421,2026-02-28,8641.28,1865.55,6775.73,15,Kimberly,Townsend,675-60-1361,...,True,3.0,HR,7575.916667,0.784112,0.215888,0.09375,1.140625,1,-0.031652
428,429,429,2026-02-28,7508.56,1371.84,6136.72,20,Kevin,Pierce,619-14-0745,...,True,1.0,Sales,6323.000000,0.817297,0.182703,0.12500,1.187500,1,-0.006031
430,431,431,2026-02-28,4346.13,888.56,3457.57,25,Hannah,Hill,742-61-2363,...,True,3.0,HR,3520.916667,0.795551,0.204449,0.15625,1.234375,1,-0.069463
478,479,479,2026-02-28,8848.58,1365.70,7482.88,0,Matthew,Williams,875-04-4109,...,True,4.0,Finance,8848.583333,0.845659,0.154341,0.00000,1.000000,1,-0.001407
500,501,501,2026-02-28,5765.81,924.90,4840.91,20,Ghost,Employee,862-86-7867,...,True,3.0,HR,4855.416667,0.839589,0.160411,0.12500,1.187501,1,-0.000095

### Save model

In [ ]:
df.to_csv('data/payroll_with_anomalies.csv', index=False)
joblib.dump(model, 'models/isolation_forest.pkl')